---
title: "Teste de integração entre o app e o relatório em HTML"
subtitle: "Ampla"
author: "Vitor Taira"
date: "`r format(Sys.time(), '%d/%m/%Y - %H:%M:%S')`"
knitr:
  opts_chunk:
    warning: false
    message: false
output: 
  html_document:
    code_folding: hide
    highlight: tango
    self_contained: true
    theme: cerulean
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
runtime: shiny
#encoding: UTF-8
---

```{r setup, message = F, results = F, warning = F}
# Exclui todos os objetos do ambiente
rm(list = ls())
# Carrega os pacotes necessários
library(DT) # Tabelas dinâmicas
library(here) # Facilita a identificação de caminhos
library(htmltools) # Ferramentas para HTML
library(htmlwidgets) # Ferramentas de personalização do HTML
library(kableExtra) # Ferramentas para tabelas kable
library(magrittr) # Ferramentas sintáticas ao dplyr, e.g. %<>%
library(openxlsx) # Ler, escrever e editar arquivos xlsx
library(pdftools) # Extração de dados em PDF
library(plotly) # Gráficos interativos
library(readr) # Importação de arquivos, e.g. read_csv()
library(readxl) # Importação de arquivos em Excel, e.g. read_excel()
library(scales) # Ferramentas para configurar escalas em gráficos
library(shiny)
library(styler) # Formatar códigos, e.g. style_file()
library(tabulapdf) # Extrair tabelas de PDFs
library(tidyverse) # Pacotes úteis para a análise de dados, e.g. dplyr e ggplot2
library(visNetwork) # Grafos
# Define o diretório de trabalho
# setwd(here())
# Define a codificação dos caractéres
Sys.setlocale("LC_CTYPE", "en_US.UTF-8")

```

```{r}
# Place the slider input and the plot output in the document.
# In a Shiny Rmd, inputs and outputs are rendered inline.
sliderInput("n", "Number of points", min = 10, max = nrow(mtcars), value = 20)
plotlyOutput("scatterPlot")
# Define the reactive plot output.
output$scatterPlot <- renderPlotly({
  # Ensure the slider value is available.
  req(input$n)

  # Create a scatter plot using the first 'n' rows of the mtcars dataset.
  plot_ly(
    data = mtcars[1:input$n, ],
    x = ~wt,
    y = ~mpg,
    type = "scatter",
    mode = "markers"
  ) %>%
    layout(
      title = "Mtcars: Weight vs MPG",
      xaxis = list(title = "Weight (1000 lbs)"),
      yaxis = list(title = "Miles/(US) gallon")
    )
})
```
